DEVICE_TREE := device/hyundai/titanlte

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := mt6735

# Platform
TARGET_BOARD_PLATFORM := mt6735
TARGET_BOARD_PLATFORM_GPU := mali

# Flags
#TARGET_GLOBAL_CFLAGS +=
#TARGET_GLOBAL_CPPFLAGS +=
#COMMON_GLOBAL_CFLAGS +=

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a15
TARGET_CPU_SMP := true

#TARGET_2ND_ARCH := arm
#TARGET_2ND_ARCH_VARIANT := armv7-a-neon
#TARGET_2ND_CPU_ABI := armeabi-v7a
#TARGET_2ND_CPU_ABI2 := armeabi
#TARGET_2ND_CPU_VARIANT := cortex-a53

# Kernel
#TARGET_KERNEL_SOURCE := kernel/hyundai/msm8996
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_HEADER_ARCH := arm
TARGET_KERNEL_CONFIG := twrp_defconfig

TARGET_PREBUILT_KERNEL := $(DEVICE_TREE)/kernel

# Boot image
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,32N2
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x04000000 --tags_offset 0x0e000000

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE     := 0x001600000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x001680000
#BOARD_SYSTEMIMAGE_PARTITION_SIZE   := 0x15D800000
#BOARD_USERDATAIMAGE_PARTITION_SIZE := 0xD0F800000
#BOARD_CACHEIMAGE_PARTITION_SIZE    := 0x04D000000
BOARD_FLASH_BLOCK_SIZE := 0x40000

# File systems
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true

# TWRP specific build flags
TW_THEME := portrait_hdpi
TW_EXCLUDE_SUPERSU := true
TW_NO_SCREEN_TIMEOUT := true
# Asian region languages
TW_EXTRA_LANGUAGES := true
TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone1/temp
